version: "3.9"
services: 
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - devlan
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_SUER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=ficha_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/database/var/lib/postgresql/data
  pgadmin:
    container_name: PGAdminCont
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=mcostasp@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"
    depends_on:
      - postgres_db        
volumes:
  postgres_db:
    driver: local


# volumes:
#   postgres_db:
#     driver: local
  # cloudbeaver:
  #   image: dbeaver/cloudbeaver:latest
  #   container_name: dbeaver    
  #   restart: "unless-stopped"
  #   ports:
  #     - "8978:8978"
  #   volumes:
  #     - cloudbeaver:/opt/cloudbeaver/workspace
  # cloudbeaver:
  #   driver: local